lyricslab/config/routes.rb
Lyricslab::Application.routes.draw do
  get "translations/new"
  get "translations/edit"
  get "home/home"
 devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } 
  
  
  
   root 'home#home'
   resources :menus
   resources :translators do
     resources :translator_translations
   end
   resources :roles do
     resources :roles_menus
   end
   resources :languages do
     resources :translations
   end
  resources :translation_types 
  resources :pricings do
    collection do
      get "show_all"
    end
  end
  

  

end

lyricslab/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.is_admin?
         can :manage, :all
      else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

lyricslab/app/models/admin.rb
class Admin < ActiveRecord::Base
end

lyricslab/app/models/language.rb
class Language < ActiveRecord::Base
has_many :translations


end

lyricslab/app/models/menu.rb
class Menu < ActiveRecord::Base
end

lyricslab/app/models/pricing.rb
class Pricing < ActiveRecord::Base
  belongs_to :translation_type
  validates :translation_type, :uniqueness => true  
end

lyricslab/app/models/role.rb
class Role < ActiveRecord::Base
  has_many :roles_menus
  
  def self.admin_menus
    Role.find(:first, :conditions => {:name => "Admin"}).roles_menus
  end
  
  
end

lyricslab/app/models/roles_menu.rb
class RolesMenu < ActiveRecord::Base
belongs_to :menu
belongs_to :role

 validates :menu_id, :uniqueness=> { scope: :role_id,
    message: "Duplicate " }
    
 scope :active, :conditions=>{:status => true}
end

lyricslab/app/models/roles_user.rb
class RolesUser < ActiveRecord::Base
end

lyricslab/app/models/translation.rb
class Translation < ActiveRecord::Base
belongs_to :language
belongs_to :translate, :foreign_key => "translate_id", :class_name => "Language"

validates :translate_id, :uniqueness => {:scope => "language_id", :message => "Duplicate"}
end

lyricslab/app/models/translation_type.rb
class TranslationType < ActiveRecord::Base

end

lyricslab/app/models/translator.rb
class Translator < ActiveRecord::Base
  has_many :translator_translations
  belongs_to :user
end

lyricslab/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
         
         
  
  # attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  has_one :translator
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    
    data = access_token['info']
   # raise access_token['info']['email'].inspect
    logger.debug "Facebook User data: #{data.inspect}"
  
    if user = User.find_by_email(data["email"])  
         
    else
     user =  User.create!(:email => data["email"], :password => Devise.friendly_token[0,20]) 
    end
    return user
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["user_hash"]
        user.email = data["email"]
      end
    end
  end  
  
 def user_menus
   if self.translator
     Role.find(:first, :conditions => {:name => "Translator"}).roles_menus.active
   else
     Role.find(:first, :conditions => {:name => "Customer"}).roles_menus
#     raise  Role.find(:first, :conditions => {:name => "Customer"}).roles_menus.inspect
   end
 end
  
     
end

lyricslab/app/controllers/translation_types_controller.rb
class TranslationTypesController < ApplicationController
  def index
    @translation_types = TranslationType.paginate(:page => params[:page], :per_page => 10, :order => "name asc")
    @count.nil? ? @count = 0 : @count = (params[:page].to_i - 1) * 10 
    #render :layout => false
  end 
  
  def show
    @translation_type = TranslationType.find(params[:id])
  end
  
  def new
    @translation_type = TranslationType.new    
  end
  
  def create
    @translation_type = TranslationType.new(translation_type_params)
    status = @translation_type.save
    if status
      redirect_to :action => "index"
    else
      render :action => "new"
    end
  end
  
  def edit
    @translation_type = TranslationType.find(params[:id])
    
  end
  
  def update
    @translation_type = TranslationType.find(params[:id]) 
    if @translation_type.update_attributes(translation_type_params)
      redirect_to :action => "index"
    else
      render :action => "edit"
      end
  end
  
  
   def destroy
    TranslationType.find(params[:id]).destroy
    redirect_to :action => 'index'
  end
  
  def add_translation
    render :layout => false
  end
  
  def translation_type_params
    params.require(:translation_type).permit(:name,:short_name,:code)
  end

end

lyricslab/app/helpers/application_helper.rb
module ApplicationHelper
def flash_class(level)
    case level
    when :notice then "info"
    when :error then "error"
    when :alert then "warning"
    end
  end
  
  
  def admin_menus
    Role.admin_menus
  end
  def user_menus(user)
    User.menus
  end

end

lyricslab/app/helpers/home_helper.rb
module HomeHelper
end

lyricslab/app/helpers/languages_helper.rb
module LanguagesHelper
end

lyricslab/app/helpers/menus_helper.rb
module MenusHelper
end

lyricslab/app/helpers/pricings_helper.rb
module PricingsHelper
end

lyricslab/app/helpers/roles_helper.rb
module RolesHelper
end

lyricslab/app/helpers/roles_menus_helper.rb
module RolesMenusHelper
end

lyricslab/app/helpers/translation_types_helper.rb
module TranslationTypesHelper
end

lyricslab/app/helpers/translators_helper.rb
module TranslatorsHelper
end

lyricslab/app/views/translation_types/_form.html.erb
  <div class="control-group"><%= f.label :name, :class => "control-label"%>
  <div class="controls"><%= f.text_field :name, :autofocus => true, :placeholder => "Translate Type Name" %></div> </div>
   <div class="control-group"><%= f.label :status, :class => "control-label"%>
 <div class="controls"><%= f.select :status, [['Active', true],['InActive', false]], {}, {:class => "selectpicker"} %> </div> </div>
 
  
  
  <div ><%= f.submit "save", :class=>"btn"%></div>
 

lyricslab/app/views/translation_types/edit.html.erb
<section class="sliceTop"> 

                    <div class="container">

                        <div class="row">
                            <div class="span12 drop-shadow lifted">
								<div class="topQuote">
									<div style="float: left">
									<h1>
									<strong>Edit Translation Type</strong>															
									</h1></div>	
                               
                                </div>
                                <div class="topBox clearfix">
                                    <div class="bigIconsColumnsWrapper">
										<article style="margin-left: auto;margin-right: auto;position: relative; padding-left: 30% !important;padding-right: 30% !important">
										<%= form_for @translation_type, :url => {:action => "update"},   :html => {:class=> "form-horizontal"}  do |f|%>
											<fieldset>
  												<legend>Edit Translation Type </legend>
											<%= render :partial => "form", :locals => {:f => f} %>
										</fieldset>
										<% end %>
                                        </article>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section> 

lyricslab/app/views/translation_types/index.html.erb
<section class="sliceTop"> 
                    <div class="container">
                        <div class="row">
                            <div class="span12 drop-shadow lifted">
								<div class="topQuote">
									<div style="float: left">
									<h1>
									<strong>Translation Types </strong>															
									</h1></div>	
                                
                                </div>
                                <div style="float: right; padding: 10px"><a class="btn btn-info" href="translation_types/new"><i class="icon-plus"> </i>Add Translation Type</a> </div>
                                <div class="topBox clearfix">
                                    <div class="bigIconsColumnsWrapper">
										<article style="margin-left: auto;margin-right: auto;position: relative; padding-left: 30%;padding-right: 30%">
											<table class="table table-striped table-bordered">
												<thead>
													<th> S.No </th>
													<th> Name </th>													
													<th> Functions </th>
												</thead>
												<tbody>
													<% if !@translation_types.empty?%>
													<% #count = 0%>
													<% @translation_types.each do |type|%>	
														<tr>
															<td><%= @count +1%></td>
															<td><%= type.name%></td>															
															<td><%= link_to raw("<i class=\"icon-edits\"> </i>Edit"), edit_translation_type_path(type), :class => "firstLevel"%> | 
																<%= link_to raw("<i =\"icon-trash\"> </i>Delete"), translation_type_path(type), :method => :delete , :confirm => "Are You Sure?", :class => "firstLevel"%>
																</td>															
															  </tr>
															  <%@count +=1 %>
													<%end%>
													<%else%>
													<tr>
														<td colspan="5"> No Records</td>
													</tr>
													<% end %>
												</tbody>
												</table>
												<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @translation_types %>
    </div>
    <%= will_paginate @translation_types, :container => false %>
  </div>
                                        </article>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section> 

lyricslab/app/views/translation_types/new.html.erb
<section class="sliceTop"> 

                    <div class="container">

                        <div class="row">
                            <div class="span12 drop-shadow lifted">
								<div class="topQuote">
									<div style="float: left">
									<h1>
									<strong>New Translate Type</strong>															
									</h1></div>	
                               
                                </div>
                                <div class="topBox clearfix">
                                    <div class="bigIconsColumnsWrapper">
										<article style="margin-left: auto;margin-right: auto;position: relative; padding-left: 30% !important;padding-right: 30% !important">
										<%= form_for @translation_type, :url => {:action => "create"},   :html => {:class=> "form-horizontal"}  do |f|%>
											<fieldset>
  												<legend>New Translate Type </legend>
											<%= render :partial => "form", :locals => {:f => f} %>
										</fieldset>
										<% end %>
                                        </article>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section> 